#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

::why::why 🤔
::girls::girls 👧
::girl::girl 👧
::like::like 😄
::vegetable::vegetable 🍆
::vegetables::vegetables 🍆🍆
::i::i 👁
::walk::walk 🚶
::walking::walking 🚶
::like::like 👍
::likes::likes 👍
::liked::liked 😍
::love::love ❤
::loves::loves 💖
::loved::loved 💖
::one::one ☝
::but::but 🍑
::booty::booty 🍑
::buts::buts 🍑
::garden::garden 🌺🌻🌸
::years::years 📅
::date::date 👫
::she::she 👩
::said::said 💬
::say::say 💬
::saying::saying 💬
::stop::stop 🛑
::stops::stops 🛑
::stopped::stopped 🛑
::can't::can't 🚫👇
::thinking::thinking 🤔💭
::think::think 🤔💭
::thinks::thinks 🤔💭
::dude::dude 😎
::when::when ⏰
::left::left 👈
::over::over 😳
::right::right 👉
::take::take 👊
::ass::ass 🍑
::butt::butt 🍑
::time::time 🕐
::posted::posted 📲
::post::post 📲
::instagram::instagram 📸💯
::lucky::lucky 🍀
::guys::guys 👨🏾
::guy::guy 👨🏾
::nut::nut 🥜
::nutted::nutted 💦
::picture::picture 📸
::pictures::pictures 📸
::old::old 👴
::boy::boy 👦
::boys::boys 🗿🗿
::story::story 📖
::orgasm::orgasm 💦
::jumped::jumped ⬆
::jump::jump ⬆
::angle::angle 📐
::body::body 💃
::two::two ✌
::week::week 📅
::day::day 📅
::lips::lips 👄
::kitchen::kitchen 🍴
::teacher::teacher 👩‍🏫
::teaching::teaching 👩‍🏫
::see::see 👀
::saw::saw 👀
::class::class 🏫
::school::school 🏫
::chair::chair 💺
::zoom::zoom ⚡
::ran::ran 🏃
::run::run 🏃
::running::running 🏃
::came::came 😳🍆💦
::god::god 😇✝
::oh::oh 🙀
::called::called 📞
::call 📞::call 📞
::slap::slap 👋🏾
::played::played 🎮
::play::play 🎮
::plays::plays 🎮
::hurry::hurry 🏃🏿‍♂️
::turkey::turkey 🦃
::big::big 😱
::biggest::biggest 😱
::scream::scream 😱
::back::back 🔙
::face::face 😀
::shoot::shoot 💦
::down::down 👇
::up::up ☝
::goodbye::goodbye 👋
::bye::bye 👋
::on::on 🔛
::load::load 💦
::saved::saved 💾
::save::save 💾
::automod::automod 🤖
::words::words 🔚
::imagine::imagine 🤔
::disabled::disabled ♿
::pastas::pastas 😩
::pasta::pasta 😩
::pic::pic 👌👀
::panties::panties 👙
::without::without ❌
::normal::normal 😐
::pussy::pussy 🐱
::spread::spread 👐
::bit::bit 😁
::send::send 📩
::sexy::sexy 🍆💦
::sex::sex 💦
::your::your 👉👈
::fingering::fingering 🖐
::yo::yo 👋
::hold::hold ✋
::lava::lava 🌋
::dick::dick 🍆
::tiny::tiny 👌🏼
::never::never 🙅
::slim::slim 😎
::ignore::ignore 😷
::hilarious::hilarious 😆
::funny::funny 😄
::atheist::atheist ⛪❌
::videogames::videogames 🎮
::understand::understand 📚
::books::books 📚
::wrong::wrong 😱❌
::search::search 🕵
::game::game 🎮
::proof::proof 📊
::logic::logic 👌
::all::all 🙆
::don't::don't ❌
::care::care 💅
::Garfield::Garfield 🐱
::anytime ⏳::anytime ⏳
::pretend::pretend 🙃
::spaghetti::spaghetti 👌
::fired::fired 🔥
::trump::trump 🍊
::porn::porn 🌽
::plane::plane ✈
::planes::planes ✈
::line::line 〰
::check::check ✅
::balls::balls 🏀
::ball::ball 🏀
::show::show 📺
::security::security 🚔
::obviously::obviously 🙄
::removed::removed 🚫
::remove::remove 🚫
::read::read 📖
::word::word 📝
::please::please 🙏
::pls::pls 🙏
::off::off 📴
::fall::fall 🍁
::go::go ☝️🏃
::camp::camp ⛺
::science::science 🔬
::best::best 🏆💯
::cried::cried 😭
::feelings::feelings 😜
::lying::lying 🤥
::text::text 📝
::bot::bot 🤖
::script::script 🤖
::fat::fat 🐋
::shit::shit 💩
::toilet::toilet 🚽
::phone::phone 📱
::reasons::reasons 🌟
::support::support ❤
::Obama::Obama 👦🏾
::speech::speech 🗣
::map::map 🗾
::appropriate::appropriate 🔞
::explain::explain 📢
::piece::piece 🍗
::hard::hard 🍆
::makes::makes 🖕
::sure::sure 💯
::real::real 💯
::xbox::xbox ❌
::advanced::advanced 💯
::emojifier::emojifier 😂
::happy::happy 😂
::fun::fun 🤗
::link::link 📎
::comment::comment 📝
::comments::comments 📝
::source::source 🍆💦
::throw::throw 🤮
::upload::upload 📂
::film::film 🎞️
::movie::movie 🎞️
::movies::movies 🎞️
::file::file 📂
::files::files 📂
::pin::pin 📌
::straight::straight 📏
::gay::gay 🌈
::lit::lit 🕯️
::nigga::nibba ❌
::nigger::nibber 😱
::fag::fag 🚬
::sleep::sleep 🛌💤
::sleeping::sleeping 💤
::boring::boring 💤
::what::what 🤨
::birthday::birthday 🥳
::party::party 🎉
::couple::couple 💑
::chungus::chungus 😍🐰
::fire::fire 🔥
::cool::cool 😎
::beans::beans 🚗✌️
::college::college 🎓
::student::student 🎓
::study::study 📜
::epic::epic 💯
::meme::meme 😂
::cum::cum 💦
::cumming::cumming 💦
::cummybot::CummyBot 🍆🍑
::slow::slow 🐌
::page::page 📄
::hey::hey 👋
::af::af 😤
::bad::bad 👎
::good::good 👌
::watch::watch 👀
::watched::watched 👀
::anime::anime 🎞️🗾
::pedo::pedo 🐻
::underage::underage 🔞
::talking::talking 👄
::talk::talk 💬 
::human::human 🧑
::being::being 👾
::value::value 📈
::values::values 📈
::reddit::reddit 🤢
::redditor::redditor 👺
::cannot::cannot 🚫
::impossible::impossible 😱
::sarcasm::sarcasm 🙃
::sarcastic::sarcastic 💁‍♂️
::space::space 🌌
::copypasta::copypasta 😩👌
::copypastas::copypastas 😩👌
::usable::usable 😬
::awesome::awesome 🔥🔥
::always::always 🕔
::heart::heart ❤️
::gun::gun 🔫
::mistake::mistake 😱
::die::die 💀
::operation::operation 🔪
::life::life ⛑
::usa::usa 🇺🇸🎇🇺🇸
::america::america 🇺🇸
::great::great 🎇
::fake::fake 🚨
::news::news 🚨
::pikachu::pikachu ⚡️
::emojify::emojify 😀
::disappear::disappear ❗️
::family::family 👨‍👩‍👧‍👦
::hope::hope 🤞
::delete::delete ❎
::deleted::deleted 🔪❎
::spez::spez 👎
::means::means 🤔
::creator::creator 😇
::emoji::emoji 😔
::cheating::cheating 😨
::cheat::cheat 💔😢
::cummy::cummy 💖
::they::they 👯
::took::took 🔫
::passion::passion 😳
::short::short 🤏
::writing::writing 📜✏️
::write::write ✏️
::essay::essay 📜
::nta::nta 🤗🤗
::yta::yta 😡😡
::angry::angry 😡
::died::died 💀
::and::and 👏
::my::my 😜
::prison::prison 🚔
::grab::grab ✊
::gang::gang 🗿
::awkward::awkward 😳
::dislike::dislike 👎
::disliked::disliked 👎
::poll::poll 📊
::now::now 👉🕑
::shame::shame 👉👈
::nsfw::nsfw 🔞💦
::posts::posts 📬
::hit::hit ✊
::front::front 🚪
::shine::shine 🎇
::absolute::absolute 💯
::absolutely::absolutely 💯
::upvote::upvote ⬆️
::upvoted::upvoted ⬆️
::downvote::downvote ⬇️
::downvoted::downvoted ⬇️
::vote::vote 🗳️
::voted::voted 🗳️
::voting::voting 🗳️
::kind::kind 😊
::kindly::kindly 😊
::singing::singing 🎤😀
::sing::sing 🎤
::flower::flower 🌼
::flowers::flowers 🌼🌺🌼
::bird::bird 🐦
::birds::birds 🐦
::seconds::seconds ⏱️
::hop::hop 🐇
::coom::coom 😤
::blood::blood 🩸
::bleed::bleed 🩸
::donation::donation 💰
::im::im 😮
::award::award 🏆
::awards::awards 🏆
::pun::pun 😳
::title::title 🤭
::little::little 🤏
::horny::horny 😉
::expensive::expensive 💰
::karen::karen 👱🏼‍♀️
::popular::popular 😎
::milk::milk 🥛
::size::size 😱
::much::much 🔥
::different::different 😡
::ugh::ugh 😩
::look::look 👀
::meat::meat 🍆
::beat::beat ✊
::chicken::chicken 🐓
::nuggets::nuggets 🍗
::bag::bag 💰
::break::break 💔
::grip::grip 💪
::magic::magic ✨
::ben::ben 🧑
::shapiro::shapiro 😍
::dog::dog 🐕
::dogs::dogs 🐕
::cat::cat 🐱
::cats::cats 🐱
::elephant::elephant 🐘
::fart::fart 😮💨
::wolf::wolf 🐺
::fox::fox 🦊
::lion::lion 🦁
::tiger::tiger 🐯
::horse::horse 🐎
::horses::horses 🐎
::pig::pig 🐖
::piggy::piggy 🐖
::pigs::pigs 🐖
::goat::goat 🐐
::mouse::mouse 🐭
::rat::rat 🐀
::bear::bear 🐻
::snake::snake 🐍
::python::python 🐍
::frog::frog 🐸
::fish::fish 🐟
::b::b 🐝
::bee::bee 🐝
::moon::moon 🌕
::sun::sun 🌞
::rain::rain ☔
::raining::raining ☔
::light::light ⚡
::snowflake::snowflake ❄️
::snowflakes::snowflakes ❄️
::liberal::liberal 😒
::liberals::liberals 😒
::university::university 🏫🎓
::farmer::farmer 🌽
::farmers::farmers 🌽
::idea::idea 💡
::ideas::ideas 💡
::note::note 📓
::spell::spell 🐝
::spelling::spelling 🐝
::original::original 🌿
::laughing::laughing 😂
::laugh::laugh 😂
::laughed::laughed 😂
::joy::joy 😂
::lol::lol 😂👌
::not::not ❌
::bazinga::bazinga 🤣
::reporter::reporter 🎤
::shout::shout 🗣️
::shouting::shouting 🗣️
::luck::luck 🍀
::based::based 👀
::cuck::cuck 👀👄
::account::account 💳
::trace::trace 🔬
::finish::finish 👅
::finishing::finishing 👅
::finished::finished 👅
::term::term 📄
::incredible::incredible 💩
::joe::joe 😳
::ask::ask 🙏
::closer::closer 😚
::close::close 🚫
::whole::whole 💦
::sleepy::sleepy 💤
::going::going 🏃
::poison::poison 🐍💀
::silence::silence 🤫
::king::king 👑
::duck::duck 🦆
::worry::worry 😟
::worried::worried 😟
::worrying::worrying 😟
::borrow::borrow 🤲
::keep::keep 🤲
::leading::leading 🥇
::donald::donald 🦆
::putin::putin 🎖️
::deal::deal 🤝
::dealing::dealing 💰
::wild::wild 🤪
::crazy::crazy 🤪
::uwu::uwu 🐱🐵🦊
::owo::owo 🦊🐱🐱
::flag::flag 🏳️
::flagged::flagged 🏳️
::red::red 🚩
::white::white 👨🏻
::blue::blue 📘
::black::black 👨🏿
::green::green 🍏
::murdering::murdering 🔪💀
::murder::murder 🔪💀
::murdered::murdered 🔪💀
::kill::kill 🔪💀
::killed::killed 🔪💀
::killing::killing 🔪💀
::knife::knife 🔪
::knives::knives 🔪🔪🔪
::young::young 👶
::younger::younger 👶
::older::older 👴
::dumb::dumb 🤤
::dumber::dumber 🤕
::fuck::fuck 🍆
::fucked::fucked 🍆😩
::fucking::fucking 🍆😩
::retard::retard 👺
::retarded::retarded 👺
::high::high 👠
::long::long 📏
::longer::longer 📏
::longest::longest 📏
::sent::sent 📩
::joke::joke 🃏
::joker::joker 🤡
::joking::joking 🃏
::watermelon::watermelon 🍉
::apple::apple 🍎
::bread::bread 🍞
::cheese::cheese 🧀
::pizza::pizza 🍕
::egg::egg 🥚
::salty::salty 🧂
::cake::cake 🍰
::cakeday::cakeday 🍰
::ice::ice 🧊
::train::train 🚆
::truck::truck 🚚
::fly::fly ✈️
::flying::flying ✈️
::airplane::airplane ✈️
::live::live ⏳
::days::days 📅 
::wife::wife 👩
::husband::husband 👨
::kid::kid 👶
::kids::kids 👶
::child::child 🧒
::children::children 🧒
::hidden::hidden 🔎
::hide::hide 🔎

::abandon::abandon 😢
::ability::ability 🤙
::abortion::abortion 😤
::above::above 🡱
::abuse::abuse 🤕
::accept::accept 🤝
::about::about 🙄
::come::come 😳
::do::do 🙆
::find::find 🧐
::get::get 😳
::give::give 🤲
::here::here 🤚
::know::know 😏
::make::make 🤑
::made::made 🤑
::man::man 🧑
::second::second 🥈
::third::third 🥉
::many::many 👅
::more::more 😨
::new::new 🣡
::no::no 🚫
::people::people 👬
::take::take 👊
::tell::tell 🗣
::that::that 👏
::you::you 👋