#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

::why::why 🤔
::girls::girls 👧
::girl::girl 👧
::like::like 😄
::vegetable::vegetable 🍆
::vegetables::vegetables 🍆🍆
::i::I 👁
::smh::smh my head
::walk::walk 🚶
::walking::walking 🚶
::like::like 👍
::likes::likes 👍
::liked::liked 😍
::love::love ❤
::loves::loves 💖
::loved::loved 💖
::one::one ☝
::but::but 🍑
::booty::booty 🍑
::buts::buts 🍑
::garden::garden 🌺🌻🌸
::years::years 📅
::date::date 👫
::she::she 👩
::said::said 💬
::say::say 💬
::saying::saying 💬
::stop::stop 🛑
::stops::stops 🛑
::stopped::stopped 🛑
::can't::can't 🚫👇
::thinking::thinking 🤔💭
::think::think 🤔💭
::thinks::thinks 🤔💭
::dude::dude 😎
::when::when ⏰
::left::left 👈
::over::over 😳
::right::right 👉
::take::take 👊
::ass::ass 🍑
::butt::butt 🍑
::time::time 🕐
::posted::posted 📲
::post::post 📲
::instagram::instagram 📸💯
::lucky:: lucky 🍀
::guys::guys 👨🏾
::guy::guy 👨🏾
::nut::nut 🥜
::nutted::nutted 💦
::picture::picture 📸
::pictures::pictures 📸
::old::old 👴
::boy::boy 👦
::boys::boys 👦
::story::story 📖
::orgasm::orgasm 💦
::jumped::jumped ⬆
::jump::jump ⬆
::angle::angle 📐
::body::body 💃
::two::two ✌
::week::week 📅
::day::day 📅
::lips::lips 👄
::kitchen::kitchen 🍴
::teacher::teacher 👩‍🏫
::teaching::teaching 👩‍🏫
::see::see 👀
::saw::saw 👀
::class::class 🏫
::school::school 🏫
::chair::chair 💺
::zoom::zoom ⚡
::ran::ran 🏃
::run::run 🏃
::running::running 🏃
::came::came 😳🍆💦
::god::god 😇✝
::oh::oh 🙀
::called::called 📞
::call 📞::call 📞
::slap::slap 👋🏾
::played::played 🎮
::play::play 🎮
::plays::plays 🎮
::hurry::hurry 🏃🏿‍♂️
::turkey::turkey 🦃
::big::big 😱
::biggest::biggest 😱
::scream::scream 😱
::back::back 🔙
::face::face 😀
::shoot::shoot 💦
::down::down 👇
::up::up ☝
::goodbye::goodbye 👋
::bye::bye 👋
::on::on 🔛
::load::load 💦
::saved::saved 💾
::save::save 💾
::automod::automod 🤖
::words::words 🔚
::imagine::imagine 🤔
::disabled::disabled ♿
::pastas::pastas 😩
::pasta::pasta 😩
::pic::pic 👌👀
::panties::panties 👙
::without::without ❌
::normal::normal 😐
::pussy::pussy 🐱
::spread::spread 👐
::bit::bit 😁
::send::send 📩
::sexy::sexy 🍆💦
::sex::sexy 💦
::your::your👉👈
::fingering::fingering 🖐
::yo::yo 👋
::hold::hold ✋
::lava::lava 🌋
::dick::dick 🍆
::tiny::tiny 👌🏼
::never::never 🙅
::slim::slim 😎
::ignore::ignore 😷
::hilarious::hilarious 😆
::funny::funny 😄
::atheist::atheist ⛪❌
::videogames::videogames 🎮
::understand::understand 📚
::books::books 📚
::wrong::wrong 😱❌
::search::search 🕵
::game::game 🎮
::proof::proof 📊
::logic::logic 👌
::all::all 💯
::don't::don't ❌
::care::care 💅
::Garfield::Garfield 🐱
::anytime ⏳::anytime ⏳
::pretend::pretend 🙃
::spaghetti::spaghetti 👌
::fired::fired 🔥
::Trump::Trump 🍊
::porn::porn 🌽
::plane::plane ✈
::planes::planes ✈
::line::line 〰
::check::check ✅
::balls::balls 🏀
::ball::ball 🏀
::show::show 📺
::security::security 🚔
::obviously::obviously 🙄
::removed::removed 🚫
::remove::remove 🚫
::read::read 📖
::word::word 📝
::please::please 🙏
::pls::pls 🙏
::off::off 📴
::fall::fall 🍁
::go::go 🏃
::camp::camp ⛺
::science::science 🔬
::best::best 🏆
::cried::cried 😭
::feelings::feelings 😜
::lying::lying 🤥
::text::text 📝
::bot::bot 🤖
::script::script 🤖
::fat::fat 🐋
::shit::shit 💩
::toilet::toilet 🚽
::phone::phone 📱
::reasons::reasons 🌟
::support::support ❤
::Obama::Obama 👦🏾
::speech::speech 🗣
::map::map 🗾
::appropriate::appropriate 🔞
::explain::explain 📢
::piece::piece 🍗
::hard::hard 🍆
::makes::makes 🖕
::sure::sure 💯
::real::real 💯
::xbox::xbox ❌
::advanced::advanced 💯
::emojifier::emojifier 😂
::happy::happy 😂
::fun::fun 🤗
::link::link 📎
::comment::comment 📝
::comments::comments 📝
::source::source 🍆💦
::throw::throw 🤮
::upload::upload 📂
::film::film 🎞️
::movie::movie 🎞️
::movies::movies 🎞️
::file::file 📂
::files::files 📂
::pin::pin 📌
::straight::straight 📏
::gay::gay 🌈
::lit::lit 🕯️
::nigga::nibba ❌
::nigger::nibber 😱
::fag::fag 🚬
::sleep::sleep 💤
::sleeping::sleeping 💤
::boring::boring 💤
::what::what 🤨
::birthday::birthday 🥳
::party::party 🎉
::couple::couple 💑
::chungus::chungus 🐰
::fire::fire 🔥
::cool::cool 😎
::beans::beans 🚗✌️
::college::college 🎓
::student::student 🎓
::study::study 📜
::epic::epic 💯
::meme::meme 😂
::cum::cum 💦
::cumming::cumming 💦
::cummybot::CummyBot 🍆🍑
::slow::slow 🐌
::page::page 📄
::hey::hey 👋
::af::af 😤
::bad::bad 👎
::good::good 👍
::watch::watch 👀
::watched::watched 👀
::anime::anime 🎞️🗾
::pedo::pedo 🐻
::underage::underage 🔞
::talking::talking 👄
::talk::talk 💬 
::human::human 🧑
::being::being 👾
::value::value 📈
::values::values 📈
::reddit::reddit 🤢
::redditor::redditor 🤠
::cannot::cannot 🚫
::impossible::impossible 😱
::sarcasm::sarcasm 🙃
::sarcastic::sarcastic 💁‍♂️
::space::space 🌌

::abandon::abandon 😢
::ability::ability 🤙
::abortion::abortion 😤
::above::above 🡱
::abuse::abuse 🤕
::accept::accept 🤝
::about::about 🙄
::come::come 😳
::do::do 🙆
::find::find 🧐
::get::get 😳
::give::give 🤲
::here::here 🤚
::know::know 😏
::make::make 🤑
::made::made 🤑
::man::man 🧑
::second::second 🥈
::third::third 🥉
::many::many 👅
::more::more 😨
::new::new 🣡
::no::no 🚫
::people::people 👬
::take::take 👊
::tell::tell 🗣
::that::that 👏
::you::you 👋